apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-release-mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: docker.io/bitnami/mysql:8.0.35-debian-11-r2
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-release-mysql
                key: mysql-root-password
        ports:
        - containerPort: 3306
