apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp
  namespace: argocd
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: abdurrahman11/nodejsapp:v6
        ports:
        - containerPort: 4000
        env:
        - name: MYSQL_HOST
          value: mysql.argocd.svc.cluster.local
        - name: MYSQL_PORT
          value: "3306"
